function openPayable(){modal('Nova conta a pagar',accountForm('pay'));bindAccount('pay')}
function openRecurringPayable(){modal('Nova conta fixa',`<form id="fixedForm" class="form-grid"><div class="field"><label>Empresa</label><select id="fBiz" required>${businessOptions(false,state.businessFilter)}</select></div><div class="field"><label>Fornecedor</label><input class="input" id="fSupplier" required></div><div class="field"><label>Categoria</label><select id="fCat" required>${categoryOptions('Saída')}</select></div><div class="field"><label>Valor padrão</label><input class="input" id="fAmount" type="number" step="0.01" min="0" required></div><div class="field span-2"><label>Descrição</label><input class="input" id="fDesc" required></div><div class="field"><label>Dia do vencimento</label><input class="input" id="fDay" type="number" min="1" max="31" value="10" required></div><div class="field"><label>Início</label><input class="input" id="fStart" type="date" value="${iso()}" required></div><div class="field"><label>Fim (opcional)</label><input class="input" id="fEnd" type="date"></div><div class="field span-2"><label>Observações</label><textarea id="fNotes"></textarea></div><div class="actions span-2"><button class="btn btn-primary">Salvar recorrência</button></div></form>`);$('fixedForm').onsubmit=async e=>{e.preventDefault();await perform(async()=>supabase.rpc('create_recurring_payable',{p_business:$('fBiz').value,p_supplier:$('fSupplier').value,p_category:$('fCat').value,p_description:$('fDesc').value,p_amount:Number($('fAmount').value),p_due_day:Number($('fDay').value),p_start_date:$('fStart').value,p_end_date:$('fEnd').value||null,p_notes:$('fNotes').value||null}),'Conta fixa cadastrada.')}}
function openReceivable(){modal('Nova conta a receber',accountForm('rec'));bindAccount('rec')}
function accountForm(kind){const pay=kind==='pay';return `<form id="accountForm" class="form-grid"><div class="field"><label>Empresa</label><select id="aBiz" required>${businessOptions(false,state.businessFilter)}</select></div><div class="field"><label>${pay?'Fornecedor':'Cliente / Origem'}</label><input class="input" id="aParty" required></div><div class="field"><label>Categoria</label><select id="aCat" required>${categoryOptions(pay?'Saída':'Entrada')}</select></div><div class="field"><label>Valor</label><input class="input" id="aAmount" type="number" step="0.01" min="0" required></div><div class="field span-2"><label>Descrição</label><input class="input" id="aDesc" required></div><div class="field"><label>Emissão</label><input class="input" id="aIssue" type="date" value="${iso()}" required></div><div class="field"><label>Vencimento</label><input class="input" id="aDue" type="date" value="${iso()}" required></div><div class="field"><label>Documento</label><input class="input" id="aDoc"></div><div class="actions span-2"><button class="btn btn-primary">Salvar</button></div></form>`}
function bindAccount(kind){$('accountForm').onsubmit=async e=>{e.preventDefault();const pay=kind==='pay';const row={business_id:$('aBiz').value,[pay?'supplier':'customer']:$('aParty').value,category:$('aCat').value,description:$('aDesc').value,document:$('aDoc').value||null,amount:Number($('aAmount').value),issue_date:$('aIssue').value,due_date:$('aDue').value,status:'Pendente'};await perform(async()=>supabase.from(pay?'payables':'receivables').insert(row),pay?'Conta a pagar cadastrada.':'Conta a receber cadastrada.')}}

function openWallet(){modal('Nova carteira',`<form id="walletForm" class="form-grid"><div class="field"><label>Empresa</label><select id="wBiz" required>${businessOptions(false,state.businessFilter)}</select></div><div class="field"><label>Tipo</label><select id="wType"><option>Banco</option><option>Caixa</option><option>Carteira Digital</option></select></div><div class="field"><label>Nome</label><input class="input" id="wName" required></div><div class="field"><label>Saldo inicial</label><input class="input" id="wOpening" type="number" step="0.01" value="0"></div><div class="actions span-2"><button class="btn btn-primary">Salvar</button></div></form>`);$('walletForm').onsubmit=async e=>{e.preventDefault();await perform(async()=>supabase.from('wallets').insert({business_id:$('wBiz').value,name:$('wName').value,type:$('wType').value,opening_balance:Number($('wOpening').value)}),'Carteira criada.')}}
function openBusiness(){modal('Nova empresa',`<form id="bizForm"><div class="field"><label>Nome da empresa</label><input class="input" id="bizName" required></div><div class="actions"><button class="btn btn-primary">Salvar</button></div></form>`);$('bizForm').onsubmit=async e=>{e.preventDefault();await perform(async()=>supabase.from('businesses').insert({name:$('bizName').value}),'Empresa cadastrada.')}}
function openCategory(){modal('Nova categoria',`<form id="catForm" class="form-grid"><div class="field"><label>Nome</label><input class="input" id="catName" required></div><div class="field"><label>Tipo</label><select id="catType"><option>Entrada</option><option>Saída</option></select></div><div class="actions span-2"><button class="btn btn-primary">Salvar</button></div></form>`);$('catForm').onsubmit=async e=>{e.preventDefault();await perform(async()=>supabase.from('categories').insert({name:$('catName').value,type:$('catType').value}),'Categoria criada.')}}
function openBankEntry(){modal('Novo item do extrato',`<form id="bankForm" class="form-grid"><div class="field"><label>Empresa</label><select id="bBiz" required>${businessOptions(false,state.businessFilter)}</select></div><div class="field"><label>Carteira</label><select id="bWallet" required></select></div><div class="field"><label>Data</label><input class="input" id="bDate" type="date" value="${iso()}" required></div><div class="field"><label>Valor do banco</label><input class="input" id="bAmount" type="number" step="0.01" required><div class="mini">Entrada positiva; saída negativa.</div></div><div class="field span-2"><label>Histórico</label><input class="input" id="bDesc" required></div><div class="actions span-2"><button class="btn btn-primary">Salvar</button></div></form>`);const sync=()=>$('bWallet').innerHTML=walletOptions($('bBiz').value);$('bBiz').onchange=sync;sync();$('bankForm').onsubmit=async e=>{e.preventDefault();await perform(async()=>supabase.from('bank_entries').insert({business_id:$('bBiz').value,wallet_id:$('bWallet').value,bank_date:$('bDate').value,description:$('bDesc').value,amount:Number($('bAmount').value)}),'Item do extrato salvo.')}}

async function submitTransfer(e){e.preventDefault();if($('trSource').value===$('trDest').value)return toast('Origem e destino precisam ser diferentes.','error');await perform(async()=>supabase.rpc('make_transfer',{p_source:$('trSource').value,p_destination:$('trDest').value,p_amount:Number($('trAmount').value),p_date:$('trDate').value,p_description:$('trDesc').value}),'Transferência realizada.')}
function openSettle(kind,id){const item=(kind==='pay'?state.payables:state.receivables).find(x=>x.id===id);modal(kind==='pay'?'Baixar pagamento':'Baixar recebimento',`<form id="settleForm" class="form-grid"><div class="field span-2"><label>${esc(item.description)}</label><strong>${fmt(item.amount)}</strong></div><div class="field"><label>Carteira</label><select id="sWallet" required>${walletOptions(item.business_id)}</select></div><div class="field"><label>Data</label><input class="input" id="sDate" type="date" value="${iso()}" required></div><div class="field"><label>Forma</label><select id="sMethod"><option>Pix</option><option>Dinheiro</option><option>Cartão Débito</option><option>Cartão Crédito</option><option>Boleto</option><option>Transferência</option></select></div><div class="actions span-2"><button class="btn btn-green">Confirmar baixa</button></div></form>`);$('settleForm').onsubmit=async e=>{e.preventDefault();const fn=kind==='pay'?'pay_payable':'receive_receivable';await perform(async()=>supabase.rpc(fn,{p_id:id,p_wallet:$('sWallet').value,p_date:$('sDate').value,p_method:$('sMethod').value}),kind==='pay'?'Pagamento registrado.':'Recebimento registrado.')}}
function openReconcile(id){const b=state.bank.find(x=>x.id===id);const candidates=state.transactions.filter(t=>t.wallet_id===b.wallet_id&&t.reconciliation_status!=='Conciliado').sort((a,c)=>Math.abs(Number(a.amount)-Math.abs(Number(b.amount)))-Math.abs(Number(c.amount)-Math.abs(Number(b.amount))));modal('Conciliar lançamento',`<p class="mini">Extrato: ${br(b.bank_date)} — ${esc(b.description)} — <b>${fmt(b.amount)}</b></p><form id="reconForm"><div class="field"><label>Lançamento correspondente</label><select id="rTx" required>${candidates.map(t=>`<option value="${t.id}">${br(t.transaction_date)} — ${esc(t.description)} — ${fmt(t.amount)} (${t.type})</option>`).join('')}</select></div><div class="actions"><button class="btn btn-primary">Conciliar</button></div></form>`);$('reconForm').onsubmit=async e=>{e.preventDefault();await perform(async()=>supabase.rpc('reconcile_bank_entry',{p_bank:id,p_transaction:$('rTx').value}),'Conciliação atualizada.')}}

async function perform(action,ok){
  try{
    const {error}=await action();
    if(error) throw error;
  }catch(e){
    console.error(e);
    toast(e.message||'Erro ao salvar.','error');
    return false;
  }

  closeModal();
  toast(ok);

  try{
    await loadAll();
  }catch(e){
    console.error('Falha ao atualizar dados após salvar:',e);
    await new Promise(r=>setTimeout(r,500));
    try{await loadAll()}catch(e2){console.error('Segunda falha ao atualizar dados:',e2)}
  }

  try{showPage(document.querySelector('.nav button.active')?.dataset.page||'dashboard')}catch(e){console.error(e)}
  return true;
}

document.addEventListener('click',async e=>{const d=e.target.closest('[data-del-tx]');if(d&&confirm('Excluir este lançamento manual?'))await perform(async()=>supabase.from('transactions').delete().eq('id',d.dataset.delTx),'Lançamento excluído.');const p=e.target.closest('[data-pay]');if(p)openSettle('pay',p.dataset.pay);const r=e.target.closest('[data-receive]');if(r)openSettle('rec',r.dataset.receive);const c=e.target.closest('[data-recon]');if(c)openReconcile(c.dataset.recon);const f=e.target.closest('[data-toggle-fixed]');if(f)await perform(async()=>supabase.rpc('toggle_recurring_payable',{p_id:f.dataset.toggleFixed,p_active:f.dataset.active!=='true'}),f.dataset.active==='true'?'Recorrência pausada.':'Recorrência reativada.');});

supabase.auth.onAuthStateChange((event,session)=>{state.session=session;if(event==='SIGNED_OUT')renderAuth();if(event==='SIGNED_IN'&&!document.querySelector('.layout'))bootstrap()});
bootstrap().catch(e=>renderFatal('Falha ao iniciar',e.message));
