function renderTransactions(){
 const arr=filtered(state.transactions);$('content').innerHTML=setTitle('Lançamentos','Entradas e saídas financeiras',`<button class="btn btn-primary" id="newTx">+ Novo lançamento</button>`)+`<div class="card"><div class="toolbar"><select id="txType"><option value="">Todos os tipos</option><option>Entrada</option><option>Saída</option></select><input class="input" id="txSearch" placeholder="Buscar descrição"></div><div id="txTable"></div></div>`;$('newTx').onclick=()=>openTransaction();$('txType').onchange=paint;$('txSearch').oninput=paint;paint();function paint(){let x=arr.filter(t=>!$('txType').value||t.type===$('txType').value).filter(t=>!$('txSearch').value||t.description.toLowerCase().includes($('txSearch').value.toLowerCase()));$('txTable').innerHTML=transactionTable(x,true)}}
function transactionTable(arr,actions=true){if(!arr.length)return '<div class="empty">Nenhum lançamento encontrado.</div>';return `<div class="table-wrap"><table class="table"><thead><tr><th>Data</th><th>Empresa</th><th>Descrição</th><th>Carteira</th><th>Tipo</th><th>Valor</th><th>Conciliação</th>${actions?'<th></th>':''}</tr></thead><tbody>${arr.map(t=>`<tr><td>${br(t.transaction_date)}</td><td>${esc(businessName(t.business_id))}</td><td>${esc(t.description)}<div class="mini">${esc(t.category||'')}</div></td><td>${esc(walletName(t.wallet_id))}</td><td>${badge(t.type)}</td><td class="${t.type==='Entrada'?'g':'r'}"><b>${t.type==='Entrada'?'+':'-'} ${fmt(t.amount)}</b></td><td>${badge(t.reconciliation_status)}</td>${actions?`<td>${t.source_type==='manual'?`<button class="btn btn-soft" data-del-tx="${t.id}">Excluir</button>`:''}</td>`:''}</tr>`).join('')}</tbody></table></div>`}

function renderPayables(){let arr=filtered(state.payables),fixed=filtered(state.recurring_payables);$('content').innerHTML=setTitle('Contas a Pagar','Controle de vencimentos, pagamentos e recorrências',`<div class="actions"><button class="btn btn-soft" id="newFixed">+ Conta fixa</button><button class="btn btn-primary" id="newPay">+ Nova conta</button></div>`)+`<div class="card" style="margin-bottom:14px"><div class="section-head"><h3>Contas fixas recorrentes</h3><span class="mini">Geração mensal automática</span></div><div id="fixedList"></div></div><div class="card"><div class="toolbar"><select id="payStatus"><option value="">Todos</option><option>Pendente</option><option>Pago</option><option>Cancelado</option></select></div><div id="payTable"></div></div>`;$('newPay').onclick=openPayable;$('newFixed').onclick=openRecurringPayable;$('payStatus').onchange=paint;paint();function paint(){let x=arr.filter(p=>!$('payStatus').value||p.status===$('payStatus').value);$('payTable').innerHTML=payableTable(x,true);$('fixedList').innerHTML=fixed.length?fixed.map(r=>`<div class="wallet-line"><span><b>${esc(r.description)}</b><small>${esc(businessName(r.business_id))} · ${esc(r.supplier)} · vence dia ${r.due_day}</small></span><span><b>${fmt(r.amount)}</b><button class="btn btn-soft" data-toggle-fixed="${r.id}" data-active="${r.active}">${r.active?'Pausar':'Reativar'}</button></span></div>`).join(''):'<div class="empty">Nenhuma conta fixa cadastrada.</div>'}}
function payableTable(arr,actions=true){if(!arr.length)return '<div class="empty">Nenhuma conta a pagar.</div>';return `<div class="table-wrap"><table class="table"><thead><tr><th>Vencimento</th><th>Empresa</th><th>Fornecedor</th><th>Descrição</th><th>Valor</th><th>Status</th>${actions?'<th></th>':''}</tr></thead><tbody>${arr.map(p=>{const st=p.status==='Pendente'&&p.due_date<iso()?'Vencido':p.status;return `<tr><td>${br(p.due_date)}</td><td>${esc(businessName(p.business_id))}</td><td>${esc(p.supplier)}</td><td>${esc(p.description)}</td><td><b>${fmt(p.amount)}</b></td><td>${badge(st)}</td>${actions?`<td>${p.status==='Pendente'?`<button class="btn btn-green" data-pay="${p.id}">Pagar</button>`:''}</td>`:''}</tr>`}).join('')}</tbody></table></div>`}

function renderReceivables(){let arr=filtered(state.receivables);$('content').innerHTML=setTitle('Contas a Receber','Controle de recebimentos',`<button class="btn btn-primary" id="newRec">+ Nova conta</button>`)+`<div class="card"><div class="toolbar"><select id="recStatus"><option value="">Todos</option><option>Pendente</option><option>Recebido</option><option>Cancelado</option></select></div><div id="recTable"></div></div>`;$('newRec').onclick=openReceivable;$('recStatus').onchange=paint;paint();function paint(){let x=arr.filter(p=>!$('recStatus').value||p.status===$('recStatus').value);$('recTable').innerHTML=receivableTable(x,true)}}
function receivableTable(arr,actions=true){if(!arr.length)return '<div class="empty">Nenhuma conta a receber.</div>';return `<div class="table-wrap"><table class="table"><thead><tr><th>Vencimento</th><th>Empresa</th><th>Cliente</th><th>Descrição</th><th>Valor</th><th>Status</th>${actions?'<th></th>':''}</tr></thead><tbody>${arr.map(p=>{const st=p.status==='Pendente'&&p.due_date<iso()?'Vencido':p.status;return `<tr><td>${br(p.due_date)}</td><td>${esc(businessName(p.business_id))}</td><td>${esc(p.customer)}</td><td>${esc(p.description)}</td><td><b>${fmt(p.amount)}</b></td><td>${badge(st)}</td>${actions?`<td>${p.status==='Pendente'?`<button class="btn btn-green" data-receive="${p.id}">Receber</button>`:''}</td>`:''}</tr>`}).join('')}</tbody></table></div>`}

function renderWallets(){const w=state.businessFilter?state.wallets.filter(x=>x.business_id===state.businessFilter):state.wallets;$('content').innerHTML=setTitle('Carteiras / Bancos','Saldo por caixa, banco e Pix',`<button class="btn btn-primary" id="newWallet">+ Nova carteira</button>`)+`<div class="wallets">${w.map(x=>`<div class="card wallet"><span class="mini">${esc(businessName(x.business_id))} · ${esc(x.type)}</span><h3>${esc(x.name)}</h3><strong>${fmt(walletBalance(x))}</strong><div class="mini">Saldo inicial: ${fmt(x.opening_balance)}</div></div>`).join('')||'<div class="empty">Nenhuma carteira.</div>'}</div>`;$('newWallet').onclick=openWallet}

function renderTransfers(){$('content').innerHTML=setTitle('Transferências','Movimentação entre carteiras sem alterar o resultado')+`<div class="grid two"><div class="card"><h3>Nova transferência</h3><form id="transferForm" class="form-grid"><div class="field"><label>Origem</label><select id="trSource" required>${walletOptions()}</select></div><div class="field"><label>Destino</label><select id="trDest" required>${walletOptions()}</select></div><div class="field"><label>Valor</label><input class="input" id="trAmount" type="number" step="0.01" min="0.01" required></div><div class="field"><label>Data</label><input class="input" id="trDate" type="date" value="${iso()}" required></div><div class="field span-2"><label>Descrição</label><input class="input" id="trDesc" value="Transferência entre carteiras"></div><div class="actions span-2"><button class="btn btn-primary">Transferir</button></div></form></div><div class="card"><h3>Histórico</h3>${transferTable()}</div></div>`;$('transferForm').onsubmit=submitTransfer}
function transferTable(){if(!state.transfers.length)return '<div class="empty">Nenhuma transferência.</div>';return `<div class="table-wrap"><table class="table"><thead><tr><th>Data</th><th>Origem</th><th>Destino</th><th>Valor</th></tr></thead><tbody>${state.transfers.map(t=>`<tr><td>${br(t.transfer_date)}</td><td>${esc(walletName(t.source_wallet_id))}</td><td>${esc(walletName(t.destination_wallet_id))}</td><td>${fmt(t.amount)}</td></tr>`).join('')}</tbody></table></div>`}

function renderReconciliation(){const bank=state.businessFilter?state.bank.filter(b=>b.business_id===state.businessFilter):state.bank;const tx=filtered(state.transactions).filter(t=>t.reconciliation_status!=='Conciliado');$('content').innerHTML=setTitle('Conciliação Bancária','Compare o extrato com os lançamentos',`<button class="btn btn-primary" id="newBank">+ Item de extrato</button>`)+`<div class="recon-grid"><div class="card"><div class="section-head"><h3>Extrato bancário</h3></div>${bankTable(bank)}</div><div class="card"><div class="section-head"><h3>Lançamentos não conciliados</h3></div>${transactionTable(tx,false)}</div></div>`;$('newBank').onclick=openBankEntry}
function bankTable(arr){if(!arr.length)return '<div class="empty">Nenhum item de extrato.</div>';return `<div class="table-wrap"><table class="table"><thead><tr><th>Data</th><th>Descrição</th><th>Valor</th><th>Status</th><th></th></tr></thead><tbody>${arr.map(b=>`<tr><td>${br(b.bank_date)}</td><td>${esc(b.description)}<div class="mini">${esc(walletName(b.wallet_id))}</div></td><td class="${Number(b.amount)>=0?'g':'r'}">${fmt(b.amount)}</td><td>${badge(b.status)}</td><td>${b.status!=='Conciliado'?`<button class="btn btn-soft" data-recon="${b.id}">Conciliar</button>`:''}</td></tr>`).join('')}</tbody></table></div>`}

function renderReports(){const tx=filtered(state.transactions).filter(t=>t.source_type!=='transfer');const byCat={};tx.filter(t=>t.type==='Saída').forEach(t=>byCat[t.category]=(byCat[t.category]||0)+Number(t.amount));$('content').innerHTML=setTitle('Relatórios','Resumo financeiro do filtro atual',`<button class="btn btn-soft" onclick="window.print()">Imprimir</button>`)+`<div class="grid three">${kpi('Receitas',fmt(tx.filter(t=>t.type==='Entrada').reduce((a,t)=>a+Number(t.amount),0)),'g')}${kpi('Despesas',fmt(tx.filter(t=>t.type==='Saída').reduce((a,t)=>a+Number(t.amount),0)),'r')}${kpi('Resultado',fmt(tx.reduce((a,t)=>a+moneySign(t),0)),'b')}</div><div class="card" style="margin-top:14px"><h3>Despesas por categoria</h3><div class="table-wrap"><table class="table"><thead><tr><th>Categoria</th><th>Valor</th></tr></thead><tbody>${Object.entries(byCat).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<tr><td>${esc(k)}</td><td>${fmt(v)}</td></tr>`).join('')}</tbody></table></div></div>`}

function renderRegisters(){$('content').innerHTML=setTitle('Cadastros','Empresas, categorias e estrutura do sistema')+`<div class="grid two"><div class="card"><div class="section-head"><h3>Empresas</h3><button class="btn btn-primary" id="addBiz">+ Empresa</button></div>${state.businesses.map(b=>`<div style="padding:10px 0;border-bottom:1px solid var(--line)">${esc(b.name)}</div>`).join('')}</div><div class="card"><div class="section-head"><h3>Categorias</h3><button class="btn btn-primary" id="addCat">+ Categoria</button></div>${state.categories.map(c=>`<div style="display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid var(--line)"><span>${esc(c.name)}</span>${badge(c.type)}</div>`).join('')}</div></div><div class="card danger-zone" style="margin-top:14px"><h3>Ambiente</h3><p class="mini">Sistema configurado para uso seguro e persistente dos dados financeiros.</p></div>`;$('addBiz').onclick=openBusiness;$('addCat').onclick=openCategory}

function modal(title,html){$('modalRoot').innerHTML=`<div class="modal-wrap" id="modalWrap"><div class="modal"><div class="modal-head"><h3>${esc(title)}</h3><button class="btn btn-soft" id="closeModal">Fechar</button></div><div class="modal-body">${html}</div></div></div>`;$('closeModal').onclick=closeModal;$('modalWrap').onclick=e=>{if(e.target.id==='modalWrap')closeModal()}}
function closeModal(){$('modalRoot').innerHTML=''}

function openTransaction(){modal('Novo lançamento',`<form id="txForm" class="form-grid"><div class="field"><label>Empresa</label><select id="mBiz" required>${businessOptions(false,state.businessFilter)}</select></div><div class="field"><label>Tipo</label><select id="mType"><option>Entrada</option><option>Saída</option></select></div><div class="field"><label>Carteira</label><select id="mWallet" required></select></div><div class="field"><label>Categoria</label><select id="mCat" required></select></div><div class="field span-2"><label>Descrição</label><input class="input" id="mDesc" required></div><div class="field"><label>Valor</label><input class="input" id="mAmount" type="number" step="0.01" min="0" required></div><div class="field"><label>Data</label><input class="input" id="mDate" type="date" value="${iso()}" required></div><div class="field"><label>Forma</label><select id="mMethod"><option>Pix</option><option>Dinheiro</option><option>Cartão Débito</option><option>Cartão Crédito</option><option>Boleto</option><option>Transferência</option></select></div><div class="field"><label>Documento</label><input class="input" id="mDoc"></div><div class="actions span-2"><button class="btn btn-primary">Salvar lançamento</button></div></form>`);const sync=()=>{$('mWallet').innerHTML=walletOptions($('mBiz').value);$('mCat').innerHTML=categoryOptions($('mType').value)};$('mBiz').onchange=sync;$('mType').onchange=sync;sync();$('txForm').onsubmit=async e=>{e.preventDefault();await perform(async()=>supabase.from('transactions').insert({business_id:$('mBiz').value,wallet_id:$('mWallet').value,type:$('mType').value,category:$('mCat').value,description:$('mDesc').value,document:$('mDoc').value||null,amount:Number($('mAmount').value),transaction_date:$('mDate').value,method:$('mMethod').value,status:$('mType').value==='Entrada'?'Recebido':'Pago'}),'Lançamento salvo.')}}
